# Generated by Django 4.2 on 2025-06-23 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openmrs_patient_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('patient_id', models.CharField(max_length=20, unique=True, verbose_name='환자번호')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('birth_date', models.DateField(verbose_name='생년월일')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('O', '기타')], max_length=1, verbose_name='성별')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='전화번호')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='이메일')),
                ('address', models.TextField(blank=True, verbose_name='주소')),
                ('guardian_name', models.CharField(blank=True, max_length=100, verbose_name='보호자 이름')),
                ('guardian_contact', models.CharField(blank=True, max_length=20, verbose_name='보호자 연락처')),
                ('guardian_relation', models.CharField(blank=True, max_length=50, verbose_name='보호자 관계')),
                ('admission_date', models.DateField(blank=True, null=True, verbose_name='입원일')),
                ('diagnosis', models.CharField(blank=True, max_length=200, null=True, verbose_name='진단명')),
                ('insurance_type', models.CharField(blank=True, max_length=50, verbose_name='보험종류')),
                ('medical_history', models.TextField(blank=True, verbose_name='병력')),
                ('special_notes', models.TextField(blank=True, verbose_name='특이사항')),
                ('blood_type', models.CharField(blank=True, max_length=5, verbose_name='혈액형')),
                ('allergies', models.TextField(blank=True, verbose_name='알레르기')),
                ('registration_date', models.DateField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.doctor', verbose_name='담당의')),
            ],
            options={
                'verbose_name': '환자',
                'verbose_name_plural': '환자',
                'ordering': ['-registration_date'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openmrs_visit_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('visit_number', models.CharField(max_length=20, unique=True, verbose_name='방문번호')),
                ('visit_type', models.CharField(choices=[('OUTPATIENT', '외래'), ('INPATIENT', '입원'), ('EMERGENCY', '응급')], max_length=20, verbose_name='방문유형')),
                ('status', models.CharField(choices=[('SCHEDULED', '예약'), ('IN_PROGRESS', '진료중'), ('COMPLETED', '완료'), ('CANCELLED', '취소')], max_length=20, verbose_name='상태')),
                ('visit_date', models.DateTimeField(verbose_name='방문일시')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='종료일시')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='진료과')),
                ('chief_complaint', models.TextField(blank=True, verbose_name='주호소')),
                ('diagnosis', models.TextField(blank=True, verbose_name='진단')),
                ('treatment_plan', models.TextField(blank=True, verbose_name='치료계획')),
                ('notes', models.TextField(blank=True, verbose_name='특이사항')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='등록일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('attending_doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='담당의')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='환자')),
            ],
            options={
                'verbose_name': '방문',
                'verbose_name_plural': '방문',
                'ordering': ['-visit_date'],
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.IntegerField(blank=True, null=True, verbose_name='수축기혈압')),
                ('diastolic_bp', models.IntegerField(blank=True, null=True, verbose_name='이완기혈압')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='심박수')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='체온')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='호흡수')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='산소포화도')),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='키(cm)')),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='체중(kg)')),
                ('measured_at', models.DateTimeField(auto_now_add=True, verbose_name='측정시간')),
                ('measured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_vitalsigns', to=settings.AUTH_USER_MODEL, verbose_name='측정자')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit', verbose_name='방문')),
            ],
            options={
                'verbose_name': '활력징후',
                'verbose_name_plural': '활력징후',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.CreateModel(
            name='NurseInitialAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=20)),
                ('pulse', models.IntegerField()),
                ('respiration', models.IntegerField()),
                ('temperature', models.FloatField()),
                ('spo2', models.IntegerField(blank=True, null=True)),
                ('consciousness', models.CharField(max_length=20)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('bmi', models.FloatField()),
                ('skin_condition', models.CharField(max_length=100)),
                ('pain_info', models.CharField(max_length=100)),
                ('diseases', models.TextField()),
                ('current_medications', models.TextField(blank=True)),
                ('drug_allergies', models.TextField(blank=True)),
                ('mobility', models.CharField(max_length=20)),
                ('eating', models.CharField(max_length=20)),
                ('excretion', models.CharField(max_length=20)),
                ('communication', models.CharField(max_length=20)),
                ('vision_hearing', models.CharField(max_length=20)),
                ('fall_risk', models.CharField(max_length=20)),
                ('infection_history', models.CharField(blank=True, max_length=100)),
                ('isolation_required', models.CharField(blank=True, max_length=100)),
                ('understanding_level', models.CharField(blank=True, max_length=100)),
                ('education_needs', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': '간호 초기 평가',
                'verbose_name_plural': '간호 초기 평가',
            },
        ),
    ]
