# Generated by Django 4.2 on 2025-06-23 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('employee_id', models.CharField(max_length=20, primary_key=True, serialize=False, unique=True, verbose_name='사원번호')),
                ('name', models.CharField(max_length=100, verbose_name='이름')),
                ('department', models.CharField(max_length=100, verbose_name='부서')),
                ('role', models.CharField(choices=[('doctor', '의사'), ('nurse', '간호사'), ('patient', '환자'), ('etc', '기타')], max_length=10, verbose_name='직무')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('openmrs_uuid', models.CharField(blank=True, max_length=36, null=True, unique=True, verbose_name='OpenMRS 환자 UUID')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_groups', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_permissions', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
