# Generated by Django 4.2 on 2025-06-23 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='부서'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', '의사'), ('nurse', '간호사'), ('patient', '환자'), ('tec', '기술자')], max_length=10, verbose_name='직무'),
        ),
    ]
