# Generated by Django 4.2 on 2025-06-23 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField()),
                ('actual_start_datetime', models.DateTimeField(blank=True, null=True)),
                ('actual_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', '예약됨'), ('checked_in', '접수완료'), ('in_progress', '진행중'), ('completed', '완료'), ('cancelled', '취소'), ('no_show', '노쇼')], default='scheduled', max_length=20)),
                ('chief_complaint', models.TextField(blank=True, verbose_name='주호소')),
                ('visit_notes', models.TextField(blank=True, verbose_name='방문 메모')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='진료과')),
                ('room_number', models.CharField(blank=True, max_length=50, verbose_name='진료실')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('openmrs_visit_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('attending_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_visits', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_visits', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='patients.patient')),
            ],
            options={
                'verbose_name': '방문',
                'verbose_name_plural': '방문들',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.CreateModel(
            name='VisitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '방문 유형',
                'verbose_name_plural': '방문 유형들',
            },
        ),
        migrations.CreateModel(
            name='VitalSigns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('systolic_bp', models.IntegerField(blank=True, null=True, verbose_name='수축기 혈압')),
                ('diastolic_bp', models.IntegerField(blank=True, null=True, verbose_name='이완기 혈압')),
                ('heart_rate', models.IntegerField(blank=True, null=True, verbose_name='심박수')),
                ('respiratory_rate', models.IntegerField(blank=True, null=True, verbose_name='호흡수')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='체온')),
                ('oxygen_saturation', models.IntegerField(blank=True, null=True, verbose_name='산소포화도')),
                ('height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='신장')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='체중')),
                ('measured_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='측정 메모')),
                ('measured_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visit_vitalsigns', to=settings.AUTH_USER_MODEL, verbose_name='측정자')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_signs', to='visits.visit')),
            ],
            options={
                'verbose_name': '바이탈 사인',
                'verbose_name_plural': '바이탈 사인들',
                'ordering': ['-measured_at'],
            },
        ),
        migrations.AddField(
            model_name='visit',
            name='visit_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visits.visittype'),
        ),
    ]
