# Generated by Django 4.2 on 2025-06-23 01:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openmrs_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VitalSession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notes', models.TextField(blank=True, help_text='세션에 대한 종합 비고', null=True)),
                ('recorded_at', models.DateTimeField(help_text='세션 기록 시간')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vital_sessions', to='openmrs_integration.openmrspatient')),
            ],
            options={
                'verbose_name': '바이탈 측정 세션',
                'verbose_name_plural': '바이탈 측정 세션들',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.CreateModel(
            name='VitalMeasurement',
            fields=[
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='measurements', serialize=False, to='vitals.vitalsession')),
                ('bp', models.CharField(max_length=20, verbose_name='혈압 (Blood Pressure)')),
                ('hr', models.PositiveIntegerField(verbose_name='심박수 (Heart Rate)')),
                ('rr', models.PositiveIntegerField(verbose_name='호흡수 (Respiratory Rate)')),
                ('temp', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='체온 (Temperature)')),
                ('spo2', models.PositiveIntegerField(verbose_name='산소포화도 (SpO2)')),
            ],
            options={
                'verbose_name': '바이탈 측정값',
                'verbose_name_plural': '바이탈 측정값들',
            },
        ),
    ]
