# Generated by Django 4.2 on 2025-06-23 01:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('openmrs_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('collected_at', models.DateTimeField()),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('lab_location', models.CharField(max_length=100)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmrs_integration.openmrspatient')),
            ],
        ),
        migrations.CreateModel(
            name='LabTestType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('unit', models.CharField(blank=True, max_length=20)),
                ('ref_low', models.CharField(blank=True, max_length=20)),
                ('ref_high', models.CharField(blank=True, max_length=20)),
                ('gender_ref', models.CharField(blank=True, max_length=20)),
                ('sort_order', models.IntegerField(default=0)),
                ('test_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='labs.labtesttype')),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('result_value', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('lab_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='labs.laborder')),
                ('test_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.labtestitem')),
            ],
        ),
        migrations.AddField(
            model_name='laborder',
            name='test_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='labs.labtesttype'),
        ),
    ]
