# Generated by Django 4.2 on 2025-06-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='labtestitem',
            name='gender_ref',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
