# Generated by Django 4.2 on 2025-06-23 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_a', models.CharField(max_length=200, verbose_name='약물A')),
                ('drug_b', models.CharField(max_length=200, verbose_name='약물B')),
                ('severity', models.CharField(choices=[('MINOR', '경미'), ('MODERATE', '중등도'), ('MAJOR', '심각'), ('CONTRAINDICATED', '금기')], max_length=20, verbose_name='심각도')),
                ('description', models.TextField(verbose_name='상호작용 설명')),
                ('mechanism', models.TextField(blank=True, verbose_name='작용기전')),
                ('clinical_effect', models.TextField(blank=True, verbose_name='임상효과')),
                ('management', models.TextField(blank=True, verbose_name='관리방법')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
            ],
            options={
                'verbose_name': '약물상호작용',
                'verbose_name_plural': '약물상호작용',
                'ordering': ['severity', 'drug_a', 'drug_b'],
                'unique_together': {('drug_a', 'drug_b')},
            },
        ),
        migrations.CreateModel(
            name='DiagnosisSupport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symptoms', models.JSONField(help_text='환자 증상 데이터', verbose_name='증상')),
                ('vital_signs', models.JSONField(help_text='활력징후 데이터', verbose_name='활력징후')),
                ('lab_results', models.JSONField(blank=True, help_text='검사결과 데이터', null=True, verbose_name='검사결과')),
                ('suggested_diagnoses', models.JSONField(help_text='AI가 제안한 진단들', verbose_name='제안진단')),
                ('confidence_scores', models.JSONField(help_text='각 진단의 신뢰도', verbose_name='신뢰도점수')),
                ('reasoning', models.TextField(help_text='AI의 추론 과정', verbose_name='추론과정')),
                ('final_diagnosis', models.TextField(blank=True, verbose_name='최종진단')),
                ('doctor_notes', models.TextField(blank=True, verbose_name='의사메모')),
                ('ai_helpful', models.BooleanField(blank=True, null=True, verbose_name='AI도움여부')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True, verbose_name='분석시간')),
                ('analyzed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='diagnosis_supports', to=settings.AUTH_USER_MODEL, verbose_name='요청의사')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='환자')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.visit', verbose_name='방문')),
            ],
            options={
                'verbose_name': '진단지원',
                'verbose_name_plural': '진단지원',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='ClinicalRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='규칙명')),
                ('description', models.TextField(verbose_name='설명')),
                ('rule_type', models.CharField(choices=[('ALERT', '경고'), ('REMINDER', '알림'), ('SUGGESTION', '제안'), ('GUIDELINE', '가이드라인')], max_length=20, verbose_name='규칙유형')),
                ('priority', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('CRITICAL', '긴급')], max_length=20, verbose_name='우선순위')),
                ('conditions', models.JSONField(help_text='규칙 적용 조건 (JSON 형태)', verbose_name='조건')),
                ('actions', models.JSONField(help_text='규칙 실행 시 수행할 액션 (JSON 형태)', verbose_name='액션')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('departments', models.CharField(blank=True, max_length=500, verbose_name='적용 진료과')),
                ('age_min', models.IntegerField(blank=True, null=True, verbose_name='최소연령')),
                ('age_max', models.IntegerField(blank=True, null=True, verbose_name='최대연령')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cdss_rules', to=settings.AUTH_USER_MODEL, verbose_name='생성자')),
            ],
            options={
                'verbose_name': '임상규칙',
                'verbose_name_plural': '임상규칙',
                'ordering': ['-priority', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CDSSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('message', models.TextField(verbose_name='메시지')),
                ('recommendation', models.TextField(blank=True, verbose_name='권장사항')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('ACKNOWLEDGED', '확인됨'), ('DISMISSED', '무시됨'), ('RESOLVED', '해결됨')], default='PENDING', max_length=20, verbose_name='상태')),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True, verbose_name='확인시간')),
                ('notes', models.TextField(blank=True, verbose_name='처리메모')),
                ('triggered_at', models.DateTimeField(auto_now_add=True, verbose_name='발생시간')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='해결시간')),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL, verbose_name='확인자')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='환자')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cdss.clinicalrule', verbose_name='적용규칙')),
                ('visit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.visit', verbose_name='방문')),
            ],
            options={
                'verbose_name': 'CDSS알림',
                'verbose_name_plural': 'CDSS알림',
                'ordering': ['-triggered_at'],
            },
        ),
    ]
