# Generated by Django 4.2 on 2025-07-03 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatsession',
            name='source_id',
            field=models.CharField(help_text='ID of the record in source_table (can be int or UUID)', max_length=50),
        ),
    ]
