# Generated by Django 4.2 on 2025-06-23 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('openmrs_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='작업 ID')),
                ('task_type', models.CharField(choices=[('COMPLICATION', '합병증 예측'), ('MORTALITY', '사망률 예측'), ('SOD2_ASSESSMENT', 'SOD2 항산화 평가'), ('IMAGE_SEGMENTATION', '이미지 병변 분할')], max_length=30, verbose_name='작업 유형')),
                ('status', models.CharField(choices=[('PENDING', '대기중'), ('PROCESSING', '처리중'), ('COMPLETED', '완료'), ('FAILED', '실패')], default='PENDING', max_length=20, verbose_name='상태')),
                ('input_data', models.JSONField(verbose_name='입력 데이터')),
                ('predictions', models.JSONField(blank=True, null=True, verbose_name='예측 결과')),
                ('confidence_scores', models.JSONField(blank=True, null=True, verbose_name='신뢰도 점수')),
                ('model_version', models.CharField(blank=True, max_length=50, verbose_name='모델 버전')),
                ('processing_time', models.FloatField(blank=True, null=True, verbose_name='처리 시간(초)')),
                ('error_message', models.TextField(blank=True, verbose_name='오류 메시지')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성일')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='완료일')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='openmrs_integration.openmrspatient', verbose_name='환자')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='요청자')),
            ],
            options={
                'verbose_name': 'AI 예측 작업',
                'verbose_name_plural': 'AI 예측 작업',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StrokeMortalityPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mortality_30_day', models.FloatField(verbose_name='30일 사망률 확률')),
                ('mortality_30_day_risk_level', models.CharField(max_length=20, verbose_name='30일 위험도')),
                ('mortality_in_hospital', models.FloatField(blank=True, null=True, verbose_name='원내 사망률')),
                ('mortality_90_day', models.FloatField(blank=True, null=True, verbose_name='90일 사망률')),
                ('mortality_1_year', models.FloatField(blank=True, null=True, verbose_name='1년 사망률')),
                ('stroke_type', models.CharField(max_length=30, verbose_name='뇌졸중 유형')),
                ('nihss_score', models.IntegerField(blank=True, null=True, verbose_name='NIHSS 점수')),
                ('reperfusion_treatment', models.BooleanField(default=False, verbose_name='재관류 치료 여부')),
                ('reperfusion_time', models.FloatField(blank=True, null=True, verbose_name='재관류 치료 시간')),
                ('risk_factors', models.JSONField(verbose_name='위험 요인들')),
                ('protective_factors', models.JSONField(blank=True, null=True, verbose_name='보호 요인들')),
                ('model_confidence', models.FloatField(verbose_name='모델 신뢰도')),
                ('model_auc', models.FloatField(verbose_name='모델 AUC')),
                ('clinical_recommendations', models.TextField(verbose_name='임상 권장사항')),
                ('monitoring_priority', models.CharField(max_length=20, verbose_name='모니터링 우선순위')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ml_models.predictiontask', verbose_name='예측 작업')),
            ],
            options={
                'verbose_name': '뇌졸중 사망률 예측',
                'verbose_name_plural': '뇌졸중 사망률 예측',
            },
        ),
        migrations.CreateModel(
            name='SOD2Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='나이')),
                ('gender', models.CharField(max_length=1, verbose_name='성별')),
                ('stroke_type', models.CharField(choices=[('ischemic_reperfusion', '허혈성 뇌졸중 (재관류 치료)'), ('ischemic_no_reperfusion', '허혈성 뇌졸중 (보존적 치료)'), ('hemorrhagic', '출혈성 뇌졸중')], max_length=30, verbose_name='뇌졸중 유형')),
                ('stroke_date', models.DateField(verbose_name='뇌졸중 발생일')),
                ('nihss_score', models.IntegerField(verbose_name='NIHSS 점수')),
                ('reperfusion_treatment', models.BooleanField(default=False, verbose_name='재관류 치료 여부')),
                ('reperfusion_time', models.FloatField(blank=True, null=True, verbose_name='재관류 치료 시간(시간)')),
                ('hours_after_stroke', models.FloatField(verbose_name='뇌졸중 후 경과 시간(시간)')),
                ('current_sod2_level', models.FloatField(verbose_name='현재 SOD2 수준')),
                ('sod2_prediction_data', models.JSONField(verbose_name='SOD2 예측 시계열 데이터')),
                ('oxidative_stress_risk', models.CharField(choices=[('low', '낮음'), ('medium', '보통'), ('high', '높음')], max_length=20, verbose_name='산화 스트레스 위험도')),
                ('prediction_confidence', models.FloatField(verbose_name='예측 신뢰도')),
                ('exercise_can_start', models.BooleanField(verbose_name='운동 시작 가능 여부')),
                ('exercise_intensity', models.IntegerField(default=0, verbose_name='권장 운동 강도(%)')),
                ('exercise_start_time', models.FloatField(blank=True, null=True, verbose_name='운동 시작 권장 시간')),
                ('sod2_target_level', models.FloatField(verbose_name='목표 SOD2 수준')),
                ('age_adjustment_factor', models.FloatField(default=1.0, verbose_name='연령 조정 계수')),
                ('stroke_type_adjustment', models.FloatField(default=1.0, verbose_name='뇌졸중 유형 조정')),
                ('nihss_adjustment', models.FloatField(default=1.0, verbose_name='NIHSS 조정 계수')),
                ('reperfusion_timing_adjustment', models.FloatField(default=1.0, verbose_name='재관류 시점 조정')),
                ('comorbidities', models.JSONField(default=list, verbose_name='동반질환')),
                ('current_medications', models.JSONField(default=list, verbose_name='현재 복용 약물')),
                ('clinical_recommendations', models.TextField(verbose_name='임상 권장사항')),
                ('exercise_recommendations', models.TextField(verbose_name='운동 권장사항')),
                ('monitoring_schedule', models.TextField(verbose_name='모니터링 일정')),
                ('task', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ml_models.predictiontask', verbose_name='평가 작업')),
            ],
            options={
                'verbose_name': 'SOD2 항산화 평가',
                'verbose_name_plural': 'SOD2 항산화 평가',
            },
        ),
        migrations.CreateModel(
            name='geneAIResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('confidence_score', models.FloatField()),
                ('model_name', models.CharField(max_length=128)),
                ('model_version', models.CharField(blank=True, max_length=32, null=True)),
                ('result_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(help_text='The patient this AI result belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='gene_ai_results', to='openmrs_integration.openmrspatient')),
            ],
            options={
                'verbose_name': 'Gene AI Result',
                'verbose_name_plural': 'Gene AI Results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplicationPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complication_type', models.CharField(choices=[('pneumonia', '폐렴'), ('acute_kidney_injury', '급성 신장 손상'), ('heart_failure', '심부전')], max_length=30, verbose_name='합병증 유형')),
                ('probability', models.FloatField(verbose_name='발생 확률')),
                ('risk_level', models.CharField(choices=[('LOW', '낮음'), ('MEDIUM', '보통'), ('HIGH', '높음'), ('CRITICAL', '매우 높음')], max_length=20, verbose_name='위험도')),
                ('threshold', models.FloatField(verbose_name='임계값')),
                ('model_auc', models.FloatField(verbose_name='모델 AUC')),
                ('model_precision', models.FloatField(verbose_name='모델 정밀도')),
                ('model_recall', models.FloatField(verbose_name='모델 재현율')),
                ('model_f1', models.FloatField(verbose_name='모델 F1 점수')),
                ('model_type', models.CharField(max_length=50, verbose_name='모델 유형')),
                ('model_strategy', models.CharField(max_length=50, verbose_name='학습 전략')),
                ('important_features', models.JSONField(verbose_name='중요 특성들')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ml_models.predictiontask', verbose_name='예측 작업')),
            ],
            options={
                'verbose_name': '합병증 예측',
                'verbose_name_plural': '합병증 예측',
                'unique_together': {('task', 'complication_type')},
            },
        ),
    ]
