# backend/ml_models/migrations/0002_alter_sod2assessment_stroke_date.py
# Generated by Django 4.2.0

from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('ml_models', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sod2assessment',
            name='stroke_date',
            field=models.DateField(blank=True, null=True, verbose_name='뇌졸중 발생일'),
        ),
    ]
