# Generated by Django 4.2 on 2025-06-25 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_models', '0002_alter_sod2assessment_stroke_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sod2assessment',
            name='stroke_date',
            field=models.DateField(default=datetime.date(2025, 6, 25), verbose_name='뇌졸중 발생일'),
            preserve_default=False,
        ),
    ]
