# Generated by Django 4.2 on 2025-06-23 01:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenMRSPatient',
            fields=[
                ('uuid', models.UUIDField(editable=False, help_text='OpenMRS Patient UUID', primary_key=True, serialize=False)),
                ('display_name', models.CharField(blank=True, help_text="Patient's full name or display name", max_length=255, null=True)),
                ('identifier', models.CharField(blank=True, help_text='Primary OpenMRS ID', max_length=100, null=True, unique=True)),
                ('given_name', models.CharField(blank=True, max_length=100, null=True)),
                ('family_name', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('raw_openmrs_data', models.JSONField(blank=True, help_text='Raw patient data from OpenMRS as JSON', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pacs_id', models.CharField(blank=True, help_text='PACS Patient ID (e.g., Orthanc ID or DICOM PatientID)', max_length=255, null=True)),
                ('user', models.OneToOneField(blank=True, db_column='user_openmrs_uuid', help_text='연결된 User 계정 (환자)의 OpenMRS UUID', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='openmrs_patient_record', to=settings.AUTH_USER_MODEL, to_field='openmrs_uuid')),
            ],
            options={
                'verbose_name': 'OpenMRS Patient Record',
                'verbose_name_plural': 'OpenMRS Patient Records',
                'ordering': ['family_name', 'given_name'],
            },
        ),
    ]
